//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumperApp.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeOfPriority
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public short Priority { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
