//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumperApp.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationComposition
    {
        public int ID { get; set; }
        public int MaterialAccountingHistoryID { get; set; }
        public int MaterialID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MaterialAccountingHistory MaterialAccountingHistory { get; set; }
    }
}
