//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumperApp.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification()
        {
            this.SpecificationComposition = new HashSet<SpecificationComposition>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int DurationInSecond { get; set; }
        public Nullable<int> PackingLength { get; set; }
        public Nullable<int> PackingWidth { get; set; }
        public Nullable<int> PackingHeight { get; set; }
        public Nullable<int> Net { get; set; }
        public Nullable<int> Gross { get; set; }
        public string QualityCertificationPath { get; set; }
        public Nullable<int> StandardID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Standard Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationComposition> SpecificationComposition { get; set; }
    }
}
